version: "3.8"
services:
  sharingmap:
    image: cr.yandex/crppopintc7ff3b906c5/sharingmap:latest
    container_name: sharingmap_${SM_ENV:-test}
    ports:
      - "${SHARINGMAP_PORT}:${SHARINGMAP_PORT}"
    env_file:
      - scripts/.env.${SM_ENV:-test}
    environment:
      - ENVIRONMENT=${SM_ENV:-test}
    volumes:
      - ~/.postgresql/root.crt:/root/.postgresql/root.crt:ro