INSERT INTO categories VALUES (0, now(), 'Все', 'all', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (1, now(), 'Для дома', 'home', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (2, now(), 'Одежда', 'clothes', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (3, now(), 'Еда', 'food', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (4, now(), 'Книги', 'books', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (5, now(), 'Детям', 'child', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (6, now(), 'Питомцам', 'pets', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (7, now(), 'Спорт', 'sport', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (8, now(), 'Техника', 'appliance', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (9, now(), 'Машина', 'auto', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (10, now(), 'Разное', 'other', now()) ON CONFLICT DO NOTHING;

INSERT INTO subcategories VALUES (1, now(), 'Отдам', 'url', 'give', now()) ON CONFLICT DO NOTHING;

INSERT INTO cities (created_at, city_name, updated_at) VALUES (now(), 'Москва', now()) ON CONFLICT DO NOTHING;
INSERT INTO cities (created_at, city_name, updated_at) VALUES (now(), 'Санкт-Петербург', now()) ON CONFLICT DO NOTHING;

INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бульвар Рокоссовского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Черкизовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Преображенская площадь', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сокольники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красносельская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Комсомольская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красные Ворота', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Чистые пруды', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лубянка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Охотный Ряд', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Библиотека имени Ленина', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кропоткинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Парк культуры', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Фрунзенская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Спортивная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Воробьёвы горы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Университет', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Проспект Вернадского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Юго-Западная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тропарёво', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Румянцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Саларьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Филатов Луг', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Прокшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ольховая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Коммунарка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ховрино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Беломорская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Речной вокзал', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Водный стадион', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Войковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сокол', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Аэропорт', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Динамо', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Белорусская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Маяковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тверская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Театральная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новокузнецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Павелецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Автозаводская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Технопарк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Коломенская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Каширская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кантемировская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Царицыно', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Орехово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Домодедовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красногвардейская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Алма-Атинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пятницкое шоссе', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Митино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Волоколамская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Мякинино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Строгино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Крылатское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Молодёжная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кунцевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Славянский бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Парк Победы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Киевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Смоленская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Арбатская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Площадь Революции', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Курская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бауманская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Электрозаводская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Семёновская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Партизанская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Измайловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Первомайская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Щёлковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Давыдково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пионерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Филёвский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Багратионовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Фили', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кутузовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Студенческая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Международная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Выставочная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Киевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Смоленская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Арбатская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Александровский сад', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Октябрьская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Добрынинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Павелецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Таганская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Проспект Мира', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новослободская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Краснопресненская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Медведково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бабушкинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Свиблово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ботанический сад', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'ВДНХ', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Алексеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Рижская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сухаревская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тургеневская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Китай-город', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Третьяковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Шаболовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ленинский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Академическая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Профсоюзная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новые Черёмушки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Калужская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Беляево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Коньково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тёплый Стан', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ясенево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новоясеневская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Планерная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сходненская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тушинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Спартак', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Щукинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Октябрьское Поле', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Полежаевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Беговая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица 1905 года', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Баррикадная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пушкинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кузнецкий Мост', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пролетарская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Волгоградский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Текстильщики', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кузьминки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Рязанский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Выхино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лермонтовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Жулебино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Котельники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Марксистская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Площадь Ильича', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Авиамоторная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Шоссе Энтузиастов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Перово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новогиреево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новокосино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Хорошёво', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Минская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ломоносовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Раменки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Мичуринский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Озёрная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Говорово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Солнцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Боровское шоссе', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новопеределкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Рассказовка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пыхтино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Аэропорт Внуково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Алтуфьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бибирево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Отрадное', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Владыкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Петровско-Разумовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тимирязевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Дмитровская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Савёловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Менделеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Цветной бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Чеховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Боровицкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Полянка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Серпуховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тульская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нагатинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нагорная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нахимовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Севастопольская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Чертановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Южная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пражская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица Академика Янгеля', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Аннино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бульвар Дмитрия Донского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Физтех', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лианозово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Яхромская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Селигерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Верхние Лихоборы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Окружная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Фонвизинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бутырская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Марьина Роща', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Достоевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Трубная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сретенский бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Чкаловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Римская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Крестьянская застава', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Дубровка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кожуховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Печатники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Волжская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Люблино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Братиславская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Марьино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Борисово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Шипиловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Зябликово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Шелепиха', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Деловой центр', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Петровский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'ЦСКА', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Хорошёвская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Народное Ополчение', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Мнёвники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Терехово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Аминьевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новаторская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Воронцовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Зюзино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Каховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Варшавская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кленовый бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нагатинский Затон', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нижегородская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лефортово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Битцевский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лесопарковая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица Старокачаловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица Скобелевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бульвар Адмирала Ушакова', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица Горчакова', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бунинская аллея', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Стахановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Окская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Юго-Восточная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Косино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Улица Дмитриевского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лухмановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Некрасовка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ростокино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Белокаменная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Локомотив', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Измайлово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Соколиная Гора', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Андроновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новохохловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Угрешская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'ЗИЛ', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Верхние Котлы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Крымская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Площадь Гагарина', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лужники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Зорге', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Панфиловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Стрешнево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Балтийская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Коптево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лихоборы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Тестовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Москва-Смоленская (Белорусский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Москва-Бутырская (Савёловский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Площадь трёх вокзалов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Москва-Курская (Курский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Москва-Товарная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Поклонная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Белорусская (Белорусский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Серп и Молот', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Чухлинка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Реутово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ипподром', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Раменское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Фабричная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Есенинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кратово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Отдых', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ильинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Быково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Удельная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Малаховка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Томилино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Панки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Люберцы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ухтомская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Вешняки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Плющево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Адроновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сортировочная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Останкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Моссельмаш', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Грачёвская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Зеленоград — Крюково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Фирсановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сходня', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Подрезково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новоподрезково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Молжаниново', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Химки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Левобережная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Апрелевка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Победа', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Крёкшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Санино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кокошкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Толстопальцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лесной Городок', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Внуково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Мичуринец', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Переделкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Солнечная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Мещерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Очаково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Матвеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кусково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Реутов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Никольское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Салтыковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Кучино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Ольгино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Железнодорожная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Подольск', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Силикатная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Остафьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Щербинка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бутово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Битца', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красный Строитель', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Покровское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Москворечье', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Курьяново', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Перерва', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Депо', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Калитники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Гражданская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красный Балтиец', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Трикотажная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Пенягино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Павшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Красногорская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Опалиха', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Аникеевка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Нахабино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Лобня', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Шереметьевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Хлебниково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Водники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Долгопрудная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Новодачная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Марк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Бескудниково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Дегунино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Рабочий Посёлок', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сетунь', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Немчиновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Сколково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Баковка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations (created_at, location_name, type, updated_at, city_id) VALUES (now(), 'Одинцово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
