INSERT INTO categories VALUES (0, now(), 'Все', 'all', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (1, now(), 'Для дома', 'home', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (2, now(), 'Одежда', 'clothes', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (3, now(), 'Еда', 'food', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (4, now(), 'Книги', 'books', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (5, now(), 'Детям', 'child', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (6, now(), 'Питомцам', 'pets', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (7, now(), 'Спорт', 'sport', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (8, now(), 'Техника', 'appliance', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (9, now(), 'Машина', 'auto', now()) ON CONFLICT DO NOTHING;
INSERT INTO categories VALUES (10, now(), 'Разное', 'other', now()) ON CONFLICT DO NOTHING;

INSERT INTO subcategories VALUES (1, now(), 'Отдам', 'url', 'give', now()) ON CONFLICT DO NOTHING;

INSERT INTO cities VALUES (1, now(), 'Москва', now()) ON CONFLICT DO NOTHING;
INSERT INTO cities VALUES (2, now(), 'Санкт-Петербург', now()) ON CONFLICT DO NOTHING;

INSERT INTO locations VALUES (1, now(), 'Бульвар Рокоссовского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (2, now(), 'Черкизовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (3, now(), 'Преображенская площадь', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (4, now(), 'Сокольники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (5, now(), 'Красносельская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (6, now(), 'Комсомольская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (7, now(), 'Красные Ворота', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (8, now(), 'Чистые пруды', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (9, now(), 'Лубянка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (10, now(), 'Охотный Ряд', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (11, now(), 'Библиотека имени Ленина', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (12, now(), 'Кропоткинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (13, now(), 'Парк культуры', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (14, now(), 'Фрунзенская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (15, now(), 'Спортивная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (16, now(), 'Воробьёвы горы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (17, now(), 'Университет', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (18, now(), 'Проспект Вернадского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (19, now(), 'Юго-Западная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (20, now(), 'Тропарёво', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (21, now(), 'Румянцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (22, now(), 'Саларьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (23, now(), 'Филатов Луг', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (24, now(), 'Прокшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (25, now(), 'Ольховая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (26, now(), 'Коммунарка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (27, now(), 'Ховрино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (28, now(), 'Беломорская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (29, now(), 'Речной вокзал', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (30, now(), 'Водный стадион', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (31, now(), 'Войковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (32, now(), 'Сокол', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (33, now(), 'Аэропорт', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (34, now(), 'Динамо', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (35, now(), 'Белорусская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (36, now(), 'Маяковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (37, now(), 'Тверская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (38, now(), 'Театральная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (39, now(), 'Новокузнецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (40, now(), 'Павелецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (41, now(), 'Автозаводская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (42, now(), 'Технопарк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (43, now(), 'Коломенская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (44, now(), 'Каширская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (45, now(), 'Кантемировская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (46, now(), 'Царицыно', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (47, now(), 'Орехово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (48, now(), 'Домодедовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (49, now(), 'Красногвардейская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (50, now(), 'Алма-Атинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (51, now(), 'Пятницкое шоссе', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (52, now(), 'Митино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (53, now(), 'Волоколамская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (54, now(), 'Мякинино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (55, now(), 'Строгино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (56, now(), 'Крылатское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (57, now(), 'Молодёжная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (58, now(), 'Кунцевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (59, now(), 'Славянский бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (60, now(), 'Парк Победы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (61, now(), 'Киевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (62, now(), 'Смоленская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (63, now(), 'Арбатская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (64, now(), 'Площадь Революции', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (65, now(), 'Курская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (66, now(), 'Бауманская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (67, now(), 'Электрозаводская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (68, now(), 'Семёновская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (69, now(), 'Партизанская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (70, now(), 'Измайловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (71, now(), 'Первомайская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (72, now(), 'Щёлковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (73, now(), 'Давыдково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (74, now(), 'Пионерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (75, now(), 'Филёвский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (76, now(), 'Багратионовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (77, now(), 'Фили', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (78, now(), 'Кутузовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (79, now(), 'Студенческая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (80, now(), 'Международная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (81, now(), 'Выставочная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (82, now(), 'Киевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (83, now(), 'Смоленская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (84, now(), 'Арбатская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (85, now(), 'Александровский сад', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (86, now(), 'Октябрьская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (87, now(), 'Добрынинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (88, now(), 'Павелецкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (89, now(), 'Таганская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (90, now(), 'Проспект Мира', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (91, now(), 'Новослободская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (92, now(), 'Краснопресненская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (93, now(), 'Медведково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (94, now(), 'Бабушкинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (95, now(), 'Свиблово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (96, now(), 'Ботанический сад', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (97, now(), 'ВДНХ', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (98, now(), 'Алексеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (99, now(), 'Рижская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (100, now(), 'Сухаревская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (101, now(), 'Тургеневская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (102, now(), 'Китай-город', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (103, now(), 'Третьяковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (104, now(), 'Шаболовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (105, now(), 'Ленинский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (106, now(), 'Академическая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (107, now(), 'Профсоюзная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (108, now(), 'Новые Черёмушки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (109, now(), 'Калужская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (110, now(), 'Беляево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (111, now(), 'Коньково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (112, now(), 'Тёплый Стан', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (113, now(), 'Ясенево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (114, now(), 'Новоясеневская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (115, now(), 'Планерная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (116, now(), 'Сходненская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (117, now(), 'Тушинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (118, now(), 'Спартак', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (119, now(), 'Щукинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (120, now(), 'Октябрьское Поле', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (121, now(), 'Полежаевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (122, now(), 'Беговая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (123, now(), 'Улица 1905 года', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (124, now(), 'Баррикадная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (125, now(), 'Пушкинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (126, now(), 'Кузнецкий Мост', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (127, now(), 'Пролетарская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (128, now(), 'Волгоградский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (129, now(), 'Текстильщики', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (130, now(), 'Кузьминки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (131, now(), 'Рязанский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (132, now(), 'Выхино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (133, now(), 'Лермонтовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (134, now(), 'Жулебино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (135, now(), 'Котельники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (136, now(), 'Марксистская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (137, now(), 'Площадь Ильича', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (138, now(), 'Авиамоторная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (139, now(), 'Шоссе Энтузиастов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (140, now(), 'Перово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (141, now(), 'Новогиреево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (142, now(), 'Новокосино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (143, now(), 'Хорошёво', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (144, now(), 'Минская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (145, now(), 'Ломоносовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (146, now(), 'Раменки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (147, now(), 'Мичуринский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (148, now(), 'Озёрная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (149, now(), 'Говорово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (150, now(), 'Солнцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (151, now(), 'Боровское шоссе', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (152, now(), 'Новопеределкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (153, now(), 'Рассказовка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (154, now(), 'Пыхтино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (155, now(), 'Аэропорт Внуково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (156, now(), 'Алтуфьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (157, now(), 'Бибирево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (158, now(), 'Отрадное', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (159, now(), 'Владыкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (160, now(), 'Петровско-Разумовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (161, now(), 'Тимирязевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (162, now(), 'Дмитровская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (163, now(), 'Савёловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (164, now(), 'Менделеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (165, now(), 'Цветной бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (166, now(), 'Чеховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (167, now(), 'Боровицкая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (168, now(), 'Полянка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (169, now(), 'Серпуховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (170, now(), 'Тульская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (171, now(), 'Нагатинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (172, now(), 'Нагорная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (173, now(), 'Нахимовский проспект', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (174, now(), 'Севастопольская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (175, now(), 'Чертановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (176, now(), 'Южная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (177, now(), 'Пражская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (178, now(), 'Улица Академика Янгеля', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (179, now(), 'Аннино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (180, now(), 'Бульвар Дмитрия Донского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (181, now(), 'Физтех', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (182, now(), 'Лианозово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (183, now(), 'Яхромская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (184, now(), 'Селигерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (185, now(), 'Верхние Лихоборы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (186, now(), 'Окружная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (187, now(), 'Фонвизинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (188, now(), 'Бутырская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (189, now(), 'Марьина Роща', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (190, now(), 'Достоевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (191, now(), 'Трубная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (192, now(), 'Сретенский бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (193, now(), 'Чкаловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (194, now(), 'Римская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (195, now(), 'Крестьянская застава', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (196, now(), 'Дубровка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (197, now(), 'Кожуховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (198, now(), 'Печатники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (199, now(), 'Волжская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (200, now(), 'Люблино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (201, now(), 'Братиславская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (202, now(), 'Марьино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (203, now(), 'Борисово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (204, now(), 'Шипиловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (205, now(), 'Зябликово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (206, now(), 'Шелепиха', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (207, now(), 'Деловой центр', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (208, now(), 'Петровский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (209, now(), 'ЦСКА', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (210, now(), 'Хорошёвская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (211, now(), 'Народное Ополчение', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (212, now(), 'Мнёвники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (213, now(), 'Терехово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (214, now(), 'Аминьевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (215, now(), 'Новаторская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (216, now(), 'Воронцовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (217, now(), 'Зюзино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (218, now(), 'Каховская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (219, now(), 'Варшавская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (220, now(), 'Кленовый бульвар', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (221, now(), 'Нагатинский Затон', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (222, now(), 'Нижегородская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (223, now(), 'Лефортово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (224, now(), 'Битцевский парк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (225, now(), 'Лесопарковая', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (226, now(), 'Улица Старокачаловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (227, now(), 'Улица Скобелевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (228, now(), 'Бульвар Адмирала Ушакова', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (229, now(), 'Улица Горчакова', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (230, now(), 'Бунинская аллея', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (231, now(), 'Стахановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (232, now(), 'Окская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (233, now(), 'Юго-Восточная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (234, now(), 'Косино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (235, now(), 'Улица Дмитриевского', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (236, now(), 'Лухмановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (237, now(), 'Некрасовка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (238, now(), 'Ростокино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (239, now(), 'Белокаменная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (240, now(), 'Локомотив', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (241, now(), 'Измайлово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (242, now(), 'Соколиная Гора', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (243, now(), 'Андроновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (244, now(), 'Новохохловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (245, now(), 'Угрешская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (246, now(), 'ЗИЛ', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (247, now(), 'Верхние Котлы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (248, now(), 'Крымская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (249, now(), 'Площадь Гагарина', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (250, now(), 'Лужники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (251, now(), 'Зорге', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (252, now(), 'Панфиловская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (253, now(), 'Стрешнево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (254, now(), 'Балтийская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (255, now(), 'Коптево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (256, now(), 'Лихоборы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (257, now(), 'Тестовская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (258, now(), 'Москва-Смоленская (Белорусский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (259, now(), 'Москва-Бутырская (Савёловский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (260, now(), 'Площадь трёх вокзалов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (261, now(), 'Москва-Курская (Курский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (262, now(), 'Москва-Товарная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (263, now(), 'Поклонная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (264, now(), 'Белорусская (Белорусский вокзал)', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (265, now(), 'Серп и Молот', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (266, now(), 'Чухлинка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (267, now(), 'Реутово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (268, now(), 'Ипподром', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (269, now(), 'Раменское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (270, now(), 'Фабричная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (271, now(), 'Есенинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (272, now(), 'Кратово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (273, now(), 'Отдых', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (274, now(), 'Ильинская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (275, now(), 'Быково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (276, now(), 'Удельная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (277, now(), 'Малаховка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (278, now(), 'Красково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (279, now(), 'Томилино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (280, now(), 'Панки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (281, now(), 'Люберцы', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (282, now(), 'Ухтомская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (283, now(), 'Вешняки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (284, now(), 'Плющево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (285, now(), 'Адроновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (286, now(), 'Сортировочная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (287, now(), 'Останкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (288, now(), 'Моссельмаш', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (289, now(), 'Грачёвская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (290, now(), 'Зеленоград — Крюково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (291, now(), 'Фирсановская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (292, now(), 'Сходня', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (293, now(), 'Подрезково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (294, now(), 'Новоподрезково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (295, now(), 'Молжаниново', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (296, now(), 'Химки', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (297, now(), 'Левобережная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (298, now(), 'Апрелевка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (299, now(), 'Победа', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (300, now(), 'Крёкшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (301, now(), 'Санино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (302, now(), 'Кокошкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (303, now(), 'Толстопальцево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (304, now(), 'Лесной Городок', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (305, now(), 'Внуково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (306, now(), 'Мичуринец', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (307, now(), 'Переделкино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (308, now(), 'Солнечная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (309, now(), 'Мещерская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (310, now(), 'Очаково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (311, now(), 'Матвеевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (313, now(), 'Кусково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (314, now(), 'Реутов', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (315, now(), 'Никольское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (316, now(), 'Салтыковская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (317, now(), 'Кучино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (318, now(), 'Ольгино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (319, now(), 'Железнодорожная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (320, now(), 'Подольск', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (321, now(), 'Силикатная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (322, now(), 'Остафьево', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (323, now(), 'Щербинка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (324, now(), 'Бутово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (325, now(), 'Битца', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (326, now(), 'Красный Строитель', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (327, now(), 'Покровское', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (328, now(), 'Москворечье', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (329, now(), 'Курьяново', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (330, now(), 'Перерва', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (331, now(), 'Депо', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (332, now(), 'Калитники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (333, now(), 'Гражданская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (334, now(), 'Красный Балтиец', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (335, now(), 'Трикотажная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (336, now(), 'Пенягино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (337, now(), 'Павшино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (338, now(), 'Красногорская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (339, now(), 'Опалиха', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (340, now(), 'Аникеевка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (341, now(), 'Нахабино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (342, now(), 'Лобня', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (343, now(), 'Шереметьевская', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (344, now(), 'Хлебниково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (345, now(), 'Водники', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (346, now(), 'Долгопрудная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (347, now(), 'Новодачная', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (348, now(), 'Марк', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (349, now(), 'Бескудниково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (350, now(), 'Дегунино', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (351, now(), 'Рабочий Посёлок', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (352, now(), 'Сетунь', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (353, now(), 'Немчиновка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (354, now(), 'Сколково', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (355, now(), 'Баковка', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
INSERT INTO locations VALUES (356, now(), 'Одинцово', 'METRO', now(), 1) ON CONFLICT DO NOTHING;
